version: '2'
services:
    pulsecheckapp-app:
        image: pulsecheckapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://pulsecheckapp-mssql:1433;database=tempdb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pulsecheckapp-mssql:
        extends:
            file: mssql.yml
            service: pulsecheckapp-mssql
